---
ip: "192.168.20.20"
memory: 2048
cpus: 2
provider: virtualbox

folders:
  - map: ~/Sites/silverstripe
    to: /home/vagrant/silverstripe
    type: nfs

sites:
  - map: hostess.vagrant
    to: /home/vagrant/silverstripe/silverstripe
